set default FC to gfortran
set default CC to gcc
set default CXX to g++
SASS_ROOT: /home/erosita/sw/eSASSdevel
package SASS
package EROSITA
setup complete
using Simput File: /data17s/darksim/MD/MD_1.0Gpc/cat_AGN_SIMPUT/SIMPUT_000042_1024.fit 
determine the search cone ...
calculate the visibility GTIs ...
cleaning up ...
finished successfully!

using Simput File: /data17s/darksim/MD/MD_1.0Gpc/cat_CLU_SIMPUT/SIMPUT_000042.fit 
determine the search cone ...
calculate the visibility GTIs ...
cleaning up ...
finished successfully!

Invalid parameter name in command line assignment: "clobber"
 Parameter name not found: ingtis
Error in loadGTI: could not find extension 'GTI' or 'STDGTI' in file '/data40s/erosim/eRASS/sixte/042/erass.gti'!
 (at sixt.c: 74)
ERROR: Operation not permitted
Task erosim 1.2 terminating with status 1
using Attitude File: /data40s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits 
initialize ...
Telescope 1, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_1.xml
Telescope 2, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_2.xml
Telescope 3, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_3.xml
Telescope 4, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_4.xml
Telescope 5, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_5.xml
Telescope 6, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_6.xml
Telescope 7, use XML file
/home/comparat/software/linux/sixte-2.5.10/share/sixte/instruments/srg/erosita_7.xml

cleaning up ...
make event directory
compute gti with ero_vis
['ero_vis', 'GTIfile=/data40s/erosim/eRASS/sixte/042/erass_SIMPUT_000042_1024.gti', 'Simput=/data17s/darksim/MD/MD_1.0Gpc/cat_AGN_SIMPUT/SIMPUT_000042_1024.fit', 'Exposure=31536000.000000', 'Attitude=/data40s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'TSTART=0.000000', 'dt=10.0', 'visibility_range=1.0', 'clobber=yes']
['ero_vis', 'GTIfile=/data40s/erosim/eRASS/sixte/042/erass_SIMPUT_000042.gti', 'Simput=/data17s/darksim/MD/MD_1.0Gpc/cat_CLU_SIMPUT/SIMPUT_000042.fit', 'Exposure=31536000.000000', 'Attitude=/data40s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'TSTART=0.000000', 'dt=10.0', 'visibility_range=1.0', 'clobber=yes']
merges gti files
/data40s/erosim/eRASS/sixte/042/gti.list
/data40s/erosim/eRASS/sixte/042/erass.gti
ls /data40s/erosim/eRASS/sixte/042/erass_*.gti > /data40s/erosim/eRASS/sixte/042/gti.list
mgtime ingtis=@/data40s/erosim/eRASS/sixte/042/gti.list outgti=/data40s/erosim/eRASS/sixte/042/erass.gti merge=OR clobber=yes
run sixte with erosim
Traceback (most recent call last):
  File "../simulate.py", line 203, in <module>
    data_dir).run_all()
  File "../simulate.py", line 177, in run_all
    self.run_sixte()
  File "../simulate.py", line 147, in run_sixte
    subprocess.check_call(cmd)
  File "/home/comparat/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['erosim', 'Simput=/data17s/darksim/MD/MD_1.0Gpc/cat_AGN_SIMPUT/SIMPUT_000042_1024.fit', 'Simput2=/data17s/darksim/MD/MD_1.0Gpc/cat_CLU_SIMPUT/SIMPUT_000042.fit[IMGSCAL>0]', 'Prefix=/data40s/erosim/eRASS/sixte/042/erass_', 'Attitude=/data40s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'GTIFile=/data40s/erosim/eRASS/sixte/042/erass.gti', 'TSTART=0.0', 'Exposure=31536000.0', 'MJDREF=51543.875', 'dt=10.0', 'Seed=42', 'clobber=yes', 'chatter=3', 'Background=yes']' returned non-zero exit status 1.
Parameter EvtFile: file "/data01s/erosim/eRASS/sixte/042/erass_ccd1_evt.fits" is not accessible in mode er.
Error in getpar: failed reading the name of the input pattern list!
 (at sixt.c: 74)
ERROR: Operation not permitted
Task ero_calevents 0.20 terminating with status 1
initialization ...
cleaning up ...
['ero_calevents', 'Projection=AIT', 'Attitude=/data01s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'clobber=yes', 'EvtFile=/data01s/erosim/eRASS/sixte/042/erass_ccd1_evt.fits', 'eroEvtFile=/data01s/erosim/eRASS/sixte/042/cal_erass_ccd1_evt.fits', 'CCDNr=1', 'RA=1.5', 'Dec=0.0']
Traceback (most recent call last):
  File "../pre-process-esass.py", line 92, in <module>
    PrepareForEsass(ra_cen, dec_cen, data_dir).prep_and_merge()
  File "../pre-process-esass.py", line 81, in prep_and_merge
    self.cal_events()
  File "../pre-process-esass.py", line 42, in cal_events
    subprocess.check_call(cmd)
  File "/home/comparat/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ero_calevents', 'Projection=AIT', 'Attitude=/data01s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'clobber=yes', 'EvtFile=/data01s/erosim/eRASS/sixte/042/erass_ccd1_evt.fits', 'eroEvtFile=/data01s/erosim/eRASS/sixte/042/cal_erass_ccd1_evt.fits', 'CCDNr=1', 'RA=1.5', 'Dec=0.0']' returned non-zero exit status 1.
 evtool: v1.31/2.1 eSASSdevel Sep 3 16:38:28 2019
 evtool/validate_tEvtool: **STOP** infile /data40s/erosim/eRASS/sixte/042/merged_erass.fits does not exist
 evtool: FAILED
['/data40s/erosim/eRASS/sixte/042/products/021_EventList_post.fits'] /data40s/erosim/eRASS/sixte/042/products/ 1 post
['evtool', 'eventfiles=/data40s/erosim/eRASS/sixte/042/merged_erass.fits', 'outfile=/data40s/erosim/eRASS/sixte/042/products/021_EventList_post.fits', 'emin=0.1', 'emax=0.5', 'image=yes', 'rebin=128', 'size=4096', 'pattern=15']
Traceback (most recent call last):
  File "../esass.py", line 374, in <module>
    esass_pipeline.run_pipeline()
  File "../esass.py", line 117, in run_pipeline
    subprocess.check_call(cmd)
  File "/home/comparat/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['evtool', 'eventfiles=/data40s/erosim/eRASS/sixte/042/merged_erass.fits', 'outfile=/data40s/erosim/eRASS/sixte/042/products/021_EventList_post.fits', 'emin=0.1', 'emax=0.5', 'image=yes', 'rebin=128', 'size=4096', 'pattern=15']' returned non-zero exit status 1.
